qrPersonalApp-main/deneme/Controllers/CreateController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Printing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using QRCoder;
using deneme.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace deneme.Controllers
{
    public class CreateController : Controller
    {

        // GET: /<controller>/
        DbService dbService = new DbService();
        public IActionResult Index()
        {
            return View();
        }



        [HttpPost]
        public IActionResult Index(string nameText, string lastNameText, string tcText, string telNoText)
        {
            byte[] byteQr;
            bool control = true;
            List<Personal> list = dbService.GetPersonals();

            foreach (var a in list)
            {
                if (a.tc == tcText)
                {
                    control = false;
                }
            }

            if (control == true)
            {
                dbService.AddPersonal(new Personal
                {
                    name = nameText,
                    lastName = lastNameText,
                    tc = tcText,
                    tel = telNoText
                });


                List<Personal> list2 = dbService.GetPersonals();

                foreach (var x in list2)
                {
                    if (x.tc==tcText)
                    {
                        string idQRData = x.id.ToString();
                        using (MemoryStream ms = new MemoryStream())
                        {
                            QRCodeGenerator qRCodeGenerator = new QRCodeGenerator();
                            QRCodeData qRCodeData = qRCodeGenerator.CreateQrCode(idQRData, QRCodeGenerator.ECCLevel.Q);
                            QRCode oQRCode = new QRCode(qRCodeData);
                            using (Bitmap oBitmap = oQRCode.GetGraphic(20))
                            {
                                oBitmap.Save(ms, ImageFormat.Png);
                                ViewBag.QRCode = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());

                                byteQr = ImageToByteArray(oBitmap);
                            }
                        }


                        dbService.AddQr(new Qr
                        {
                            perId = x.id,
                            qrByte = byteQr
                        });
                    }
                }

                ViewBag.control = true;
            }
            else
            {
                ViewBag.control = false;
            }

            
            ViewBag.nameTxt = nameText;
            ViewBag.lastNameTxt = lastNameText;
            ViewBag.tcTxt = tcText;
            ViewBag.telNoTxt = telNoText;

            

            return View();
        }



        public static byte[] ImageToByteArray(Image img)
        {
            using (var stream = new MemoryStream())
            {
                img.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }

    }
}

qrPersonalApp-main/deneme/Views/Create/Index.cshtml
@{
    ViewData["Title"] = "Ekle";
}

<div class="container-sm" style="text-align: center; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);">
    @using (Html.BeginForm("Index", "Create", FormMethod.Post))
    {
    <div class="container container-sm mt-2 d-flex flex-column justify-content-center align-items-center" style="border-radius: 5px; padding:2.5rem;">
        <div class="d-flex justify-content-center align-items-center">
            <div class="d-flex flex-column justify-content-center align-items-center">
                <p class="mt-3" style="font-weight: bold; color: white; font-size: 1.2rem;">Personel Adı: </p>
                <input type="text" name="nameText" style="padding: 12px; border: 2px solid black; border-radius: 4px; box-sizing: border-box; box-shadow: 0 15px 20px -10px rgba(0,0,0,0.5);" placeholder="İsim giriniz.."/>
                <p class="mt-3" style="font-weight: bold; color: white; font-size: 1.2rem;">Personel TC: </p>
                <input type="text" name="tcText" maxlength="11" style="padding: 12px; border: 2px solid black; border-radius: 4px; box-sizing: border-box; box-shadow: 0 15px 20px -10px rgba(0,0,0,0.5);" placeholder="TC giriniz.."/>
            </div>
            <div class="d-flex flex-column justify-content-center align-items-center" style="margin-left:80px;">
                <p class="mt-3" style="font-weight: bold; color: white; font-size: 1.2rem; ">Personel Soyadı: </p>
                <input type="text" name="lastNameText" style="padding: 12px; border: 2px solid black; border-radius: 4px; box-sizing: border-box; box-shadow: 0 15px 20px -10px rgba(0,0,0,0.5);" placeholder="Soyisim giriniz.."/>
                <p class="mt-3" style="font-weight: bold; color: white; font-size: 1.2rem; ">Personel Tel No: </p>
                <input type="tel" name="telNoText" class="telefon_maskeli" style="padding: 12px; border: 2px solid black; border-radius: 4px; box-sizing: border-box; box-shadow: 0 15px 20px -10px rgba(0,0,0,0.5);" />
            </div>
        </div>
        <br />
        <input class="btn btn-success" type="submit" value="Olustur" style="color: white; font-weight: bold; padding: 20px 40px; margin-top: 25px; border: 1px solid black; box-shadow: 0 15px 20px -10px rgba(0,0,0,0.5);" />
    </div>
    }
    <br />
    <div class="container-sm mt-2 d-flex justify-content-center align-items-center">
        @if (ViewBag.control == true)
        {
            @if (ViewBag.QRCode != null)
            {
                <table class="table table-dark table-sm">
                    <thead>
                        <tr>
                            <td style="color: gold; text-align: center;">Personel</td>
                            <td style="color: gold; text-align: center;">TC No</td>
                            <td style="color: gold; text-align: center;">Tel No</td>
                            <td style="color: gold; text-align: center;">QR Kod</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td style="text-align: center; vertical-align: middle;">@ViewBag.nameTxt @ViewBag.lastNameTxt</td>
                            <td style="text-align: center; vertical-align: middle;">@ViewBag.tcTxt</td>
                            <td style="text-align: center; vertical-align: middle;">@ViewBag.telNoTxt</td>
                            <td style="text-align: center; vertical-align: middle;"><img src="@ViewBag.QRCode" style="width:200px;height:200px;" /></td>
                        </tr>
                    </tbody>
                </table>
            }
        }
        @if (ViewBag.control == false)
        {
            <p style="color:red;font-weight:bold;font-size:2.5rem;">Personel Zaten Eklenmiş!</p>
        }

    </div>
</div>

<script>$(document).ready(function () {
            $('.telefon').mask('(000) 000-00-00');
            $('.telefon_maskeli').mask('(000) 000-00-00', {
                placeholder: "(___) ___-__-__"
            });
        });</script>